apiVersion: apps/v1
kind: Deployment
metadata:
  name: agree-io
  labels:
    app: agree-io
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agree-io
  template:
    metadata:
      labels:
        app: agree-io
    spec:
      containers:
      - name: agree-io
        image: 554386539706.dkr.ecr.us-east-1.amazonaws.com/agree-io:latest
        env:
        - name: RAILS_ENV
          value: "test"
        ports:
        - containerPort: 3000