apiVersion: apps/v1
kind: Deployment
metadata:
  name: agree-io
  labels:
    app: agree-io
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agree-io
  template:
    metadata:
      labels:
        app: agree-io
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: agree-io
        image: 554386539706.dkr.ecr.us-east-1.amazonaws.com/agree-io:$VERSION
        imagePullPolicy: "Always"
        env:
        - name: RAILS_ENV
          value: $ENVIRONMENT
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20